#!/usr/bin/env node
/**
 * sync-chrome.mjs — puts the ONE site header and footer on every page.
 *
 *   node tools/sync-chrome.mjs           apply
 *   node tools/sync-chrome.mjs --check   report pages that are out of date (exit 1)
 *
 * Source of truth: partials/header.html, partials/footer.html,
 * assets/site-chrome.css, assets/site-chrome.js. Pages carry the markup between
 * <!-- SITE-HEADER:START/END --> and <!-- SITE-FOOTER:START/END --> markers;
 * this script rewrites what is between them. Never hand-edit those regions.
 *
 * The first run on a page that predates the shared chrome migrates it: the old
 * header (`<nav id="navbar">` + its mobile menu, or the `site-bar` strip) and the
 * old `<footer>` are removed and replaced by the markers. Legacy noindex pages
 * (demo, poc) are left alone on purpose.
 */
import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const SKIP = new Set(['demo.html', 'poc.html'])
const CHECK = process.argv.includes('--check')

const header = fs.readFileSync(path.join(ROOT, 'partials/header.html'), 'utf8').trim()
const footer = fs.readFileSync(path.join(ROOT, 'partials/footer.html'), 'utf8').trim()
const H = ['<!-- SITE-HEADER:START (generated by tools/sync-chrome.mjs — edit partials/header.html) -->', '<!-- SITE-HEADER:END -->']
const F = ['<!-- SITE-FOOTER:START (generated by tools/sync-chrome.mjs — edit partials/footer.html) -->', '<!-- SITE-FOOTER:END -->']
const CSS = '<link rel="stylesheet" href="/assets/site-chrome.css">'
const JS = '<script src="/assets/site-chrome.js" defer></script>'

function pages(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(e => {
    const p = path.join(dir, e.name)
    if (e.isDirectory()) return ['.git', 'node_modules', 'partials', 'tools', 'assets'].includes(e.name) ? [] : pages(p)
    return e.name.endsWith('.html') && !SKIP.has(e.name) ? [p] : []
  })
}

const count = (s, re) => (s.match(re) || []).length
const block = (m, body) => `${m[0]}\n${body}\n${m[1]}`
const escape = s => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
const between = m => new RegExp(`${escape(m[0])}[\\s\\S]*?${escape(m[1])}`)

let changed = 0, problems = 0
for (const file of pages(ROOT)) {
  const rel = path.relative(ROOT, file)
  const before = fs.readFileSync(file, 'utf8')
  let html = before

  if (!html.includes(H[0])) {
    // --- one-time migration of a legacy header ---
    const nav = html.match(/(?:[ \t]*<!--\s*NAV\s*-->\s*)?<nav id="navbar">[\s\S]*?<\/nav>/)
    const bar = html.match(/<div class="site-bar">[\s\S]*?<\/div>/)
    const old = nav || bar
    if (old) html = html.replace(old[0], block(H, header))
    else html = html.replace(/<body([^>]*)>/, `<body$1>\n${block(H, header)}`)
    html = html.replace(/(?:[ \t]*<!--\s*MOBILE MENU\s*-->\s*)?<div class="mobile-menu" id="mobileMenu">[\s\S]*?<\/div>\s*/, '')
  } else {
    html = html.replace(between(H), block(H, header))
  }

  if (!html.includes(F[0])) {
    const oldFooter = html.match(/(?:[ \t]*<!--\s*FOOTER\s*-->\s*)?<footer[\s\S]*?<\/footer>/)
    if (oldFooter) html = html.replace(oldFooter[0], block(F, footer))
    else html = html.replace(/<\/body>/, `${block(F, footer)}\n</body>`)
  } else {
    html = html.replace(between(F), block(F, footer))
  }

  if (!html.includes(CSS)) html = html.replace('</head>', `  ${CSS}\n</head>`)
  if (!html.includes(JS)) html = html.replace('</body>', `  ${JS}\n</body>`)

  // Structural sanity: the blocks swapped in and out must be balanced.
  const delta = s => count(s, /<div\b/g) - count(s, /<\/div>/g)
  if (delta(html) !== delta(before)) { problems++; console.error(`!! ${rel}: <div> balance changed (${delta(before)} → ${delta(html)}) — not written`); continue }
  if (count(html, /<header class="mc-header"/g) !== 1 || count(html, /<footer class="mc-footer"/g) !== 1) { problems++; console.error(`!! ${rel}: expected exactly one site header and footer — not written`); continue }

  if (html !== before) {
    changed++
    if (CHECK) console.log(`out of date: ${rel}`)
    else { fs.writeFileSync(file, html, 'utf8'); console.log(`updated: ${rel}`) }
  }
}
console.log(`${changed} page(s) ${CHECK ? 'out of date' : 'updated'}${problems ? `, ${problems} problem(s)` : ''}`)
process.exit(problems || (CHECK && changed) ? 1 : 0)
